[package]
name = "cs4999-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
clio = { version = "0.3.5", features = ["clap-parse"] }
enum_dispatch = "0.3.13"
peg = "0.8.5"
petgraph = "0.8.3"
